const stateCodeMap = {
    "AL": "ALABAMA",
    "AK": "ALASKA",
    "AS": "AMERICAN SAMOA",
    "AZ": "ARIZONA",
    "AR": "ARKANSAS",
    "CA": "CALIFORNIA",
    "CO": "COLORADO",
    "CT": "CONNECTICUT",
    "DE": "DELAWARE",
    "DC": "DISTRICT OF COLUMBIA",
    "FL": "FLORIDA",
    "GA": "GEORGIA",
    "GU": "GUAM",
    "HI": "HAWAII",
    "ID": "IDAHO",
    "IL": "ILLINOIS",
    "IN": "INDIANA",
    "IA": "IOWA",
    "KS": "KANSAS",
    "KY": "KENTUCKY",
    "LA": "LOUISIANA",
    "ME": "MAINE",
    "MH": "MARSHALL ISLANDS",
    "MD": "MARYLAND",
    "MA": "MASSACHUSETTS",
    "MI": "MICHIGAN",
    "MN": "MINNESOTA",
    "MS": "MISSISSIPPI",
    "MO": "MISSOURI",
    "MT": "MONTANA",
    "NE": "NEBRASKA",
    "NV": "NEVADA",
    "NH": "NEW HAMPSHIRE",
    "NJ": "NEW JERSEY",
    "NM": "NEW MEXICO",
    "NY": "NEW YORK",
    "NC": "NORTH CAROLINA",
    "ND": "NORTH DAKOTA",
    "OH": "OHIO",
    "OK": "OKLAHOMA",
    "OR": "OREGON",
    "PW": "PALAU",
    "PA": "PENNSYLVANIA",
    "PR": "PUERTO RICO",
    "RI": "RHODE ISLAND",
    "SC": "SOUTH CAROLINA",
    "SD": "SOUTH DAKOTA",
    "TN": "TENNESSEE",
    "TX": "TEXAS",
    "UT": "UTAH",
    "VT": "VERMONT",
    "VI": "VIRGIN ISLANDS",
    "VA": "VIRGINIA",
    "WA": "WASHINGTON",
    "WV": "WEST VIRGINIA",
    "WI": "WISCONSIN",
    "WY": "WYOMING"
};

const stateNameMap = {
    "ALABAMA": "AL",
    "ALASKA": "AK",
    "AMERICAN SAMOA": "AS",
    "ARIZONA": "AZ",
    "ARKANSAS": "AR",
    "CALIFORNIA": "CA",
    "COLORADO": "CO",
    "CONNECTICUT": "CT",
    "DELAWARE": "DE",
    "DISTRICT OF COLUMBIA": "DC",
    "FLORIDA": "FL",
    "GEORGIA": "GA",
    "GUAM": "GU",
    "HAWAII": "HI",
    "IDAHO": "ID",
    "ILLINOIS": "IL",
    "INDIANA": "IN",
    "IOWA": "IA",
    "KANSAS": "KS",
    "KENTUCKY": "KY",
    "LOUISIANA": "LA",
    "MAINE": "ME",
    "MARSHALL ISLANDS": "MH",
    "MARYLAND": "MD",
    "MASSACHUSETTS": "MA",
    "MICHIGAN": "MI",
    "MINNESOTA": "MN",
    "MISSISSIPPI": "MS",
    "MISSOURI": "MO",
    "MONTANA": "MT",
    "NEBRASKA": "NE",
    "NEVADA": "NV",
    "NEW HAMPSHIRE": "NH",
    "NEW JERSEY": "NJ",
    "NEW MEXICO": "NM",
    "NEW YORK": "NY",
    "NORTH CAROLINA": "NC",
    "NORTH DAKOTA": "ND",
    "OHIO": "OH",
    "OKLAHOMA": "OK",
    "OREGON": "OR",
    "PALAU": "PW",
    "PENNSYLVANIA": "PA",
    "PUERTO RICO": "PR",
    "RHODE ISLAND": "RI",
    "SOUTH CAROLINA": "SC",
    "SOUTH DAKOTA": "SD",
    "TENNESSEE": "TN",
    "TEXAS": "TX",
    "UTAH": "UT",
    "VERMONT": "VT",
    "VIRGIN ISLANDS": "VI",
    "VIRGINIA": "VA",
    "WASHINGTON": "WA",
    "WEST VIRGINIA": "WV",
    "WISCONSIN": "WI",
    "WYOMING": "WY"
};

// GENC2 standard country codes
const countryCodeMap = {
    "DZ": "ALGERIA",
    "AO": "ANGOLA",
    "BJ": "BENIN",
    "BW": "BOTSWANA",
    "BF": "BURKINA FASO",
    "BI": "BURUNDI",
    "CM": "CAMEROON",
    "CV": "CAPE VERDE",
    "CF": "CENTRAL AFRICAN REPUBLIC",
    "TD": "CHAD",
    "KM": "COMOROS",
    "CD": "CONGO DEMOCRATIC REPUBLIC",
    "CG": "REPUBLIC OF THE CONGO",
    "DJ": "DJIBOUTI",
    "EG": "EGYPT",
    "GQ": "EQUATORIAL GUINEA",
    "ER": "ERITREA",
    "ET": "ETHIOPIA",
    "GA": "GABON",
    "GM": "GAMBIA",
    "GH": "GHANA",
    "GN": "GUINEA",
    "GW": "GUINEA-BISSAU",
    "CI": "IVORY COAST",
    "KE": "KENYA",
    "LS": "LESOTHO",
    "LR": "LIBERIA",
    "LY": "LIBYA",
    "MG": "MADAGASCAR",
    "MW": "MALAWI",
    "ML": "MALI",
    "MR": "MAURITANIA",
    "MU": "MAURITIUS",
    "YT": "MAYOTTE",
    "MA": "MOROCCO",
    "MZ": "MOZAMBIQUE",
    "NA": "NAMIBIA",
    "NE": "NIGER",
    "NG": "NIGERIA",
    "RE": "REUNION",
    "RW": "RWANDA",
    "SH": "SAINT HELENA",
    "ST": "SAO TOME AND PRINCIPE",
    "SN": "SENEGAL",
    "SC": "SEYCHELLES",
    "SL": "SIERRA LEONE",
    "SO": "SOMALIA",
    "ZA": "SOUTH AFRICA",
    "SS": "SOUTH SUDAN",
    "SD": "SUDAN",
    "SZ": "SWAZILAND",
    "TZ": "TANZANIA",
    "TG": "TOGO",
    "TN": "TUNISIA",
    "UG": "UGANDA",
    "EH": "WESTERN SAHARA",
    "ZM": "ZAMBIA",
    "ZW": "ZIMBABWE",
    "BD": "BANGLADESH",
    "BT": "BHUTAN",
    "BN": "BRUNEI",
    "MM": "MYANMAR",
    "KH": "CAMBODIA",
    "CN": "CHINA",
    "GU": "GUAM",
    "HK": "HONG KONG",
    "IN": "INDIA",
    "ID": "INDONESIA",
    "JP": "JAPAN",
    "KP": "KOREA, NORTH",
    "KR": "KOREA, SOUTH",
    "LA": "LAOS",
    "MO": "MACAO",
    "MY": "MALAYSIA",
    "MV": "MALDIVES",
    "MN": "MONGOLIA",
    "NP": "NEPAL",
    "MP": "NORTHERN MARIANA ISLANDS",
    "PK": "PAKISTAN",
    "PW": "PALAU",
    "PG": "PAPUA NEW GUINEA",
    "PH": "PHILIPPINES",
    "SG": "SINGAPORE",
    "SB": "SOLOMON ISLANDS",
    "LK": "SRI LANKA",
    "TW": "TAIWAN",
    "TH": "THAILAND",
    "TL": "TIMOR-LESTE",
    "VN": "VIETNAM",
    "QZ": "AKROTIRI",
    "AL": "ALBANIA",
    "AM": "ARMENIA",
    "AD": "ANDORRA",
    "AT": "AUSTRIA",
    "AZ": "AZERBAIJAN",
    "BY": "BELARUS",
    "BE": "BELGIUM",
    "BA": "BOSNIA AND HERZEGOVINA",
    "BG": "BULGARIA",
    "HR": "CROATIA",
    "CY": "CYPRUS",
    "CZ": "CZECH REPUBLIC",
    "DK": "DENMARK",
    "XD": "DHEKELIA",
    "EE": "ESTONIA",
    "FO": "FAROE ISLANDS",
    "FI": "FINLAND",
    "FR": "FRANCE",
    "GE": "GEORGIA",
    "DE": "GERMANY",
    "GI": "GIBRALTAR",
    "GR": "GREECE",
    "GG": "GUERNSEY",
    "HU": "HUNGARY",
    "IS": "ICELAND",
    "IE": "IRELAND",
    "IM": "ISLE OF MAN",
    "IT": "ITALY",
    "JE": "JERSEY",
    "KZ": "KAZAKHSTAN",
    "KG": "KYRGYZSTAN",
    "LV": "LATVIA",
    "LI": "LIECHTENSTEIN",
    "LT": "LITHUANIA",
    "LU": "LUXEMBOURG",
    "MK": "MACEDONIA",
    "MT": "MALTA",
    "MD": "MOLDOVA",
    "MC": "MONACO",
    "ME": "MONTENEGRO",
    "NL": "NETHERLANDS",
    "NO": "NORWAY",
    "PL": "POLAND",
    "PT": "PORTUGAL",
    "RO": "ROMANIA",
    "RU": "RUSSIA",
    "SM": "SAN MARINO",
    "RS": "SERBIA",
    "SK": "SLOVAKIA",
    "SI": "SLOVENIA",
    "ES": "SPAIN",
    "XR": "SVALBARD AND JAN MAYEN ISLANDS",
    "SE": "SWEDEN",
    "CH": "SWITZERLAND",
    "TJ": "TAJIKISTAN",
    "TR": "TURKEY",
    "TM": "TURKMENISTAN",
    "UA": "UKRAINE",
    "GB": "UNITED KINGDOM",
    "UZ": "UZBEKISTAN",
    "VA": "VATICAN CITY",
    "AF": "AFGHANISTAN",
    "BH": "BAHRAIN",
    "XG": "GAZA STRIP",
    "IR": "IRAN",
    "IQ": "IRAQ",
    "IL": "ISRAEL",
    "JO": "JORDAN",
    "KW": "KUWAIT",
    "LB": "LEBANON",
    "OM": "OMAN",
    "PS": "PALESTINIAN TERRITORY",
    "QA": "QATAR",
    "SA": "SAUDI ARABIA",
    "SY": "SYRIA",
    "AE": "UNITED ARAB EMIRATES",
    "XW": "WEST BANK",
    "YE": "YEMEN",
    "CA": "CANADA",
    "GL": "GREENLAND",
    "MX": "MEXICO",
    "PR": "PUERTO RICO*",
    "PM": "SAINT PIERRE AND MIQUELON",
    "US": "UNITED STATES",
    "VI": "VIRGIN ISLANDS, U.S.",
    "AS": "AMERICAN SAMOA",
    "AU": "AUSTRALIA",
    "CK": "COOK ISLANDS",
    "FJ": "FIJI",
    "PJ": "FRENCH POLYNESIA",
    "TF": "FRENCH SOUTHERN AND ANTARCTIC ISLANDS",
    "KI": "KIRIBATI",
    "MH": "MARSHALL ISLANDS",
    "FM": "MICRONESIA, FEDERATED STATES OF",
    "QM": "MIDWAY ISLAND",
    "NR": "NAURU",
    "NC": "NEW CALEDONIA",
    "NZ": "NEW ZEALAND",
    "NU": "NIUE",
    "NF": "NORFOLK ISLAND",
    "PN": "PITCAIRN ISLANDS",
    "WS": "WESTERN SAMOA",
    "TK": "TOKELAU",
    "TO": "TONGA",
    "TV": "TUVALU",
    "VU": "VANUATU",
    "QW": "WAKE ISLAND",
    "WF": "WALLIS AND FUTUNA",
    "AI": "ANGUILLA",
    "AG": "ANTIGUA AND BARBUDA",
    "AR": "ARGENTINA",
    "AW": "ARUBA",
    "BS": "BAHAMAS",
    "BB": "BARBADOS",
    "BZ": "BELIZE",
    "BM": "BERMUDA",
    "BO": "BOLIVIA",
    "BR": "BRAZIL",
    "BQ": "CARIBBEAN NETHERLANDS",
    "KY": "CAYMAN ISLANDS",
    "CL": "CHILE",
    "CO": "COLOMBIA",
    "CR": "COSTA RICA",
    "CU": "CUBA",
    "CUW": "CURACAO",
    "DM": "DOMINICA",
    "DO": "DOMINICAN REPUBLIC",
    "EC": "ECUADOR",
    "SV": "EL SALVADOR",
    "FK": "FALKLAND ISLANDS",
    "GF": "FRENCH GUIANA",
    "GD": "GRENADA",
    "GP": "GUADELOUPE",
    "A2": "GUANTANAMO BAY",
    "GT": "GUATEMALA",
    "GY": "GUYANA",
    "HT": "HAITI",
    "HN": "HONDURAS",
    "JM": "JAMAICA",
    "MQ": "MARTINIQUE",
    "MS": "MONTSERRAT",
    "NI": "NICARAGUA",
    "PA": "PANAMA",
    "PY": "PARAGUAY",
    "PE": "PERU",
    "BL": "SAINT BARTHALEMY",
    "KN": "SAINT KITTS AND NEVIS ISLANDS",
    "LC": "SAINT LUCIA",
    "MF": "SAINT MARTIN",
    "VC": "SAINT VINCENT AND THE GRENADINES",
    "SX": "SINT MAARTEN",
    "SR": "SURINAME",
    "TT": "TRINIDAD AND TOBAGO",
    "TC": "TURKS AND CAICOS ISLANDS",
    "UY": "URUGUAY",
    "VE": "VENEZUELA",
    "VG": "BRITISH VIRGIN ISLANDS"
};

// GENC2 standard country codes
const countryNameMap = {
    "ALGERIA": "DZ",
    "ANGOLA": "AO",
    "BENIN": "BJ",
    "BOTSWANA": "BW",
    "BURKINA FASO": "BF",
    "BURUNDI": "BI",
    "CAMEROON": "CM",
    "CAPE VERDE": "CV",
    "CENTRAL AFRICAN REPUBLIC": "CF",
    "CHAD": "TD",
    "COMOROS": "KM",
    "CONGO DEMOCRATIC REPUBLIC": "CD",
    "KINSHASA": "CD",
    "REPUBLIC OF THE BRAZZAVILLE": "CG",
    "REPUBLIC OF THE CONGO": "CG",
    "DJIBOUTI": "DJ",
    "EGYPT": "EG",
    "EQUATORIAL GUINEA": "GQ",
    "ERITREA": "ER",
    "ETHIOPIA": "ET",
    "GABON": "GA",
    "GAMBIA": "GM",
    "GHANA": "GH",
    "GUINEA": "GN",
    "GUINEA-BISSAU": "GW",
    "IVORY COAST": "CI",
    "CÔTE D'IVOIRE": "CI",
    "KENYA": "KE",
    "LESOTHO": "LS",
    "LIBERIA": "LR",
    "LIBYA": "LY",
    "MADAGASCAR": "MG",
    "MALAWI": "MW",
    "MALI": "ML",
    "MAURITANIA": "MR",
    "MAURITIUS": "MU",
    "MAYOTTE": "YT",
    "MOROCCO": "MA",
    "MOZAMBIQUE": "MZ",
    "NAMIBIA": "NA",
    "NIGER": "NE",
    "NIGERIA": "NG",
    "REUNION": "RE",
    "RWANDA": "RW",
    "SAINT HELENA": "SH",
    "SAO TOME AND PRINCIPE": "ST",
    "SENEGAL": "SN",
    "SEYCHELLES": "SC",
    "SIERRA LEONE": "SL",
    "SOMALIA": "SO",
    "SOUTH AFRICA": "ZA",
    "SOUTH SUDAN": "SS",
    "SUDAN": "SD",
    "SWAZILAND": "SZ",
    "TANZANIA": "TZ",
    "TOGO": "TG",
    "TUNISIA": "TN",
    "UGANDA": "UG",
    "WESTERN SAHARA": "EH",
    "ZAMBIA": "ZM",
    "ZIMBABWE": "ZW",
    "BANGLADESH": "BD",
    "BHUTAN": "BT",
    "BRUNEI": "BN",
    "BURMA": "MM",
    "MYANMAR": "MM",
    "CAMBODIA": "KH",
    "CHINA": "CN",
    "GUAM": "GU",
    "HONG KONG": "HK",
    "INDIA": "IN",
    "INDONESIA": "ID",
    "JAPAN": "JP",
    "KOREA, NORTH": "KP",
    "KOREA, SOUTH": "KR",
    "LAOS": "LA",
    "MACAO": "MO",
    "MALAYSIA": "MY",
    "MALDIVES": "MV",
    "MONGOLIA": "MN",
    "NEPAL": "NP",
    "NORTHERN MARIANA ISLANDS": "MP",
    "PAKISTAN": "PK",
    "PALAU": "PW",
    "PAPUA NEW GUINEA": "PG",
    "PHILIPPINES": "PH",
    "SINGAPORE": "SG",
    "SOLOMON ISLANDS": "SB",
    "SRI LANKA": "LK",
    "TAIWAN": "TW",
    "THAILAND": "TH",
    "TIMOR-LESTE": "TL",
    "VIETNAM": "VN",
    "AKROTIRI": "QZ",
    "ALBANIA": "AL",
    "ARMENIA": "AM",
    "ANDORRA": "AD",
    "AUSTRIA": "AT",
    "AZERBAIJAN": "AZ",
    "BELARUS": "BY",
    "BELGIUM": "BE",
    "BOSNIA AND HERZEGOVINA": "BA",
    "BULGARIA": "BG",
    "CROATIA": "HR",
    "CYPRUS": "CY",
    "CZECH REPUBLIC": "CZ",
    "DENMARK": "DK",
    "DHEKELIA": "XD",
    "ESTONIA": "EE",
    "FAROE ISLANDS": "FO",
    "FINLAND": "FI",
    "FRANCE": "FR",
    "GEORGIA": "GE",
    "GERMANY": "DE",
    "GIBRALTAR": "GI",
    "GREECE": "GR",
    "GUERNSEY": "GG",
    "HUNGARY": "HU",
    "ICELAND": "IS",
    "IRELAND": "IE",
    "ISLE OF MAN": "IM",
    "ITALY": "IT",
    "JERSEY": "JE",
    "KAZAKHSTAN": "KZ",
    "KYRGYZSTAN": "KG",
    "LATVIA": "LV",
    "LIECHTENSTEIN": "LI",
    "LITHUANIA": "LT",
    "LUXEMBOURG": "LU",
    "MACEDONIA": "MK",
    "MALTA": "MT",
    "MOLDOVA": "MD",
    "MONACO": "MC",
    "MONTENEGRO": "ME",
    "NETHERLANDS": "NL",
    "NORWAY": "NO",
    "POLAND": "PL",
    "PORTUGAL": "PT",
    "ROMANIA": "RO",
    "RUSSIA": "RU",
    "SAN MARINO": "SM",
    "SERBIA": "RS",
    "SLOVAKIA": "SK",
    "SLOVENIA": "SI",
    "SPAIN": "ES",
    "SVALBARD AND JAN MAYEN ISLANDS": "XR",
    "SWEDEN": "SE",
    "SWITZERLAND": "CH",
    "TAJIKISTAN": "TJ",
    "TURKEY": "TR",
    "TURKMENISTAN": "TM",
    "UKRAINE": "UA",
    "UNITED KINGDOM": "GB",
    "UZBEKISTAN": "UZ",
    "VATICAN CITY": "VA",
    "AFGHANISTAN": "AF",
    "BAHRAIN": "BH",
    "GAZA STRIP": "XG",
    "IRAN": "IR",
    "IRAQ": "IQ",
    "ISRAEL": "IL",
    "JORDAN": "JO",
    "KUWAIT": "KW",
    "LEBANON": "LB",
    "OMAN": "OM",
    "PALESTINIAN TERRITORY": "PS",
    "QATAR": "QA",
    "SAUDI ARABIA": "SA",
    "SYRIA": "SY",
    "UNITED ARAB EMIRATES": "AE",
    "WEST BANK": "XW",
    "YEMEN": "YE",
    "CANADA": "CA",
    "GREENLAND": "GL",
    "MEXICO": "MX",
    "PUERTO RICO*": "PR",
    "SAINT PIERRE AND MIQUELON": "PM",
    "UNITED STATES": "US",
    "VIRGIN ISLANDS, U.S.": "VI",
    "AMERICAN SAMOA": "AS",
    "AUSTRALIA": "AU",
    "COOK ISLANDS": "CK",
    "FIJI": "FJ",
    "FRENCH POLYNESIA": "PJ",
    "FRENCH SOUTHERN AND ANTARCTIC ISLANDS": "TF",
    "KIRIBATI": "KI",
    "MARSHALL ISLANDS": "MH",
    "MICRONESIA, FEDERATED STATES OF": "FM",
    "MIDWAY ISLAND": "QM",
    "NAURU": "NR",
    "NEW CALEDONIA": "NC",
    "NEW ZEALAND": "NZ",
    "NIUE": "NU",
    "NORFOLK ISLAND": "NF",
    "PITCAIRN ISLANDS": "PN",
    "SAMOA": "WS",
    "WESTERN SAMOA": "WS",
    "TOKELAU": "TK",
    "TONGA": "TO",
    "TUVALU": "TV",
    "VANUATU": "VU",
    "WAKE ISLAND": "QW",
    "WALLIS AND FUTUNA": "WF",
    "ANGUILLA": "AI",
    "ANTIGUA AND BARBUDA": "AG",
    "ARGENTINA": "AR",
    "ARUBA": "AW",
    "BAHAMAS": "BS",
    "BARBADOS": "BB",
    "BELIZE": "BZ",
    "BERMUDA": "BM",
    "BOLIVIA": "BO",
    "BONAIRE": "BQ",
    "BRAZIL": "BR",
    "CARIBBEAN NETHERLANDS": "BQ",
    "CAYMAN ISLANDS": "KY",
    "CHILE": "CL",
    "COLOMBIA": "CO",
    "COSTA RICA": "CR",
    "CUBA": "CU",
    "CURACAO": "CUW",
    "DOMINICA": "DM",
    "DOMINICAN REPUBLIC": "DO",
    "ECUADOR": "EC",
    "EL SALVADOR": "SV",
    "FALKLAND ISLANDS": "FK",
    "ISLAS MALVINAS": "FK",
    "FRENCH GUIANA": "GF",
    "GRENADA": "GD",
    "GUADELOUPE": "GP",
    "GUANTANAMO BAY": "A2",
    "GUATEMALA": "GT",
    "GUYANA": "GY",
    "HAITI": "HT",
    "HONDURAS": "HN",
    "JAMAICA": "JM",
    "MARTINIQUE": "MQ",
    "MONTSERRAT": "MS",
    "NICARAGUA": "NI",
    "PANAMA": "PA",
    "PARAGUAY": "PY",
    "PERU": "PE",
    "SAINT BARTHALEMY": "BL",
    "SAINT KITTS AND NEVIS ISLANDS": "KN",
    "SAINT LUCIA": "LC",
    "SAINT MARTIN": "MF",
    "SAINT VINCENT AND THE GRENADINES": "VC",
    "SINT MAARTEN": "SX",
    "SURINAME": "SR",
    "TRINIDAD AND TOBAGO": "TT",
    "TURKS AND CAICOS ISLANDS": "TC",
    "URUGUAY": "UY",
    "VENEZUELA": "VE",
    "VIRGIN ISLANDS": "VG",
    "BRITISH VIRGIN ISLANDS": "VG"
};


/* 
    Parse the city, state, and country from a string
    Does not work if input has a street address, zip code, etc

    returns object 
        "Dallas, Texas"          => { city: "Dallas", state: "TX", country: "US" }
        "London, United Kingdom" => { city: "London", state: null, country: "GB" }
        "London"                 => { city: "London", state: null, country: null }
*/  
const parseCityStateCountryFromString = (cityState) => {
    const trimmedCityState = cityState.trim();
    let wordArr = trimmedCityState.replace(",",", ").split(" ").filter(word => word !== "");

    // if there is only 1 word, 
    // then assume its a city and there is no state/country
    if (wordArr.length === 1) {
        return { city: wordArr[0].trim().replace(",",""), state: null, country: null };
    }
    
    // if the last word is a state/country abbreviation
    if (wordArr[wordArr.length-1].length <= 3 ) {
        // assume city is all words before abbr, remove commma if exists
        const possibleCity = wordArr.slice(0, wordArr.length - 1).join(" ").replace(",", "").trim(); 
        const possibleAbbr = wordArr[wordArr.length-1].toUpperCase();
        if (stateCodeMap[possibleAbbr]) {
            return {
                city: possibleCity,
                state: possibleAbbr,
                country: "US"
            }
        }
        if (countryCodeMap[possibleAbbr]) {
            return {
                city: possibleCity,
                state: null,
                country: possibleAbbr
            }
        }
    }

    // if the last 1 to 5 words are a state or country
    for (let i=1; i<=5; i++) {
        // if the wordArr length is greater than the number of words being checked, 
        // then we can assume there is still a city before the state/country being checked
        if (wordArr.length <= i) continue;

        const possibleCity = wordArr.slice(0, wordArr.length-i).join(" ").replace(",", "").trim()
        const possibleName = wordArr.slice(-i).join(" ").replace(",", "").toUpperCase();
        if (stateNameMap[possibleName]) {
            return {
                city: possibleCity,
                state: stateNameMap[possibleName],
                country: "US"
            }
        }
        if (countryNameMap[possibleName]) {
            return {
                city: possibleCity,
                state: null,
                country: countryNameMap[possibleName]
            }
        }
    }

    // else there is no state or country
    return {
        city: wordArr.join(" ").replace(",","").trim(),
        state: null,
        country: null
    }
}

module.exports = {
    stateCodeMap,
    stateNameMap,
    countryCodeMap,
    countryNameMap,
    parseCityStateCountryFromString
}